Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{
    [HandleError(View = "Error")]
    [ValueReporter]
    public class PhotoController : Controller
    {
        private PhotoSharingContext context = new PhotoSharingContext();

        // GET: Photo
        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;
            if (number == 0)
            {
                photos = context.Photos.ToList();
            }
            else
            {
                photos = (
                from p in context.Photos
                orderby p.CreatedDate descending select p).Take(number).ToList();
            }
            return PartialView("_PhotoGallery", photos);
        }

        [HttpGet]
        public ActionResult Display(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);

        }

        public ActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.CreatedDate = DateTime.Today;
            if (!ModelState.IsValid)
            {
                return View("Create", photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType =
                    image.ContentType;
                    photo.PhotoFile = new
                    byte[image.ContentLength];
                    image.InputStream.Read(
                    photo.PhotoFile, 0,
                    image.ContentLength);
                }
            }
            context.Photos.Add(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Delete", photo);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = context.Photos.Find(id);
            context.Photos.Remove(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo != null)
            {
                return File(photo.PhotoFile,
                photo.ImageMimeType);
            }
            else
            {
                return null;
            }

        }
        public ActionResult SlideShow() 
         {
            throw new NotImplementedException("The SlideShow action is not yet ready");
         }




    }
}

Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/PhotoSharingStyles.css" rel="stylesheet" />
     <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>    
        <h1 class="site-page-title">
            Adventure Works Photo Sharing
        </h1>
        <div class="clear-floats" />
        <div id="topmenu">
            <nav>
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Quiénes somos</a></li>
                    <li><a href="#">Servicios</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contacto</a></li>
                </ul>
            </nav>
        </div>
        <div id="breadcrumb">
            @Html.ActionLink("Add your photo", "Create", "Photo")
        </div>
        <div>
            @RenderBody()
        </div>
</body>
</html>

Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model)
{
<div class="photo-index-card">
    <h3>"@item.Title"</h3>

    @if (item.PhotoFile != null)
    {
    <img class="photo-index-card-img" src="@Url.Action("GetImage", "Photo", new { id = item.PhotoID })" />
    }
    <div class="photo-metadata">

        <div>
            <span class="display-label">
                Created By:
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.UserName)
            </span>
        </div>

        <div>
            <span class="display-label">
                Created On:
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.CreatedDate)
            </span>
        </div>

    </div>

    @Html.ActionLink("Display", "Display", new { id = item.PhotoID }) 
    @Html.ActionLink("Delete", "Delete", new { id = item.PhotoID })
</div>
    }